name: cozzite
description: Bazzite + COSMIC + security.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: vscode.yml
  - from-file: cosmic-rpm.yml
  - from-file: cosmic-systemd.yml
  - from-file: gui-packages.yml
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: script
    scripts:
      - createautostartdir.sh
      - authselect.sh
      - httpsmirrors.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
